######################################################################
#
# File name : sccomp_tb.udo
# Created on: Sun May 23 17:18:31 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
