######################################################################
#
# File name : sccomp_tb_compile.do
# Created on: Wed Jun 09 14:40:18 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_10.4c\\win32pe\\vlib work
D:\\Modeltech_pe_10.4c\\win32pe\\vlib msim

D:\\Modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
D:\\Modeltech_pe_10.4c\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

D:\\Modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
D:\\Modeltech_pe_10.4c\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

D:\\Modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/sources_1/new/regfile.v" \
"../../../CPU31.srcs/sources_1/new/pc.v" \
"../../../CPU31.srcs/sources_1/new/mux.v" \
"../../../CPU31.srcs/sources_1/new/II.v" \
"../../../CPU31.srcs/sources_1/new/ext.v" \
"../../../CPU31.srcs/sources_1/new/control.v" \
"../../../CPU31.srcs/sources_1/new/alu.v" \
"../../../CPU31.srcs/sources_1/new/add.v" \

D:\\Modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU31.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\Modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../CPU31.srcs/sources_1/new/dmem.v" \
"../../../CPU31.srcs/sources_1/new/cpu.v" \
"../../../CPU31.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU31.srcs/sources_1/new/sccomp_tb.v" \

# compile glbl module
D:\\Modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

