######################################################################
#
# File name : sccomp_tb_wave.do
# Created on: Wed Jun 09 14:40:24 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
