######################################################################
#
# File name : sccomp_tb_simulate.do
# Created on: Wed Jun 09 14:40:24 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L dist_mem_gen_v8_0_10 -lib xil_defaultlib xil_defaultlib.sccomp_tb xil_defaultlib.glbl

do {sccomp_tb_wave.do}

view wave
view structure
view signals

do {sccomp_tb.udo}

run 1000ns
