# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/Modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Ray/Vivado/CPU31/CPU31.cache/wt [current_project]
set_property parent.project_path D:/Ray/Vivado/CPU31/CPU31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files c:/Users/14065/Desktop/CPU_31/test2019_for_cpu31.coe
add_files c:/Users/14065/Desktop/CPU_31/mips_31_mars_simulate.coe
add_files -quiet D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/regfile.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/pc.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/mux.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/II.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/ext.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/control.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/alu.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/add.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/dmem.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/cpu.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/sccomp_dataflow.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/seg7x16.v
  D:/Ray/Vivado/CPU31/CPU31.srcs/sources_1/new/onBoard.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Ray/Vivado/CPU31/CPU31.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files D:/Ray/Vivado/CPU31/CPU31.srcs/constrs_1/new/xdc.xdc]


synth_design -top onBoard -part xc7a100tcsg324-1


write_checkpoint -force -noxdef onBoard.dcp

catch { report_utilization -file onBoard_utilization_synth.rpt -pb onBoard_utilization_synth.pb }
