######################################################################
#
# File name : sccomp_tb.udo
# Created on: Wed Jun 09 14:31:27 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
